config/routes.rb
AzPollerApp::Application.routes.draw do

  resources :users
  resources :sessions, only: [ :new, :create, :destroy ]
  resources :microposts, only: [:destroy, :create]
  match "signin", to: "sessions#new", via: 'get'
  match "signout", to: "sessions#destroy", via: 'delete'
  root 'static_pages#home'
  get "help" => 'static_pages#help'
  get "signup" => "users#new"
  
  

  

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  default_scope ->{ order('created_at DESC') } # -> is to define procedures, or lambda.
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts, dependent: :destroy
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }

  before_save { self.email = email.downcase }
  before_create :create_remember_token

  has_secure_password

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def feed
      self.microposts.load
  end

  private

  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy]
  before_action :correct_user, only: :destroy

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created"
      redirect_to root_path
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end
  
  def destroy
    Micropost.find(params[:id]).destroy
    redirect_to root_path
  end
  
  private
    def micropost_params
      params.require(:micropost).permit(:content) 
    end
    
    def correct_user
      redirect_to root_url, notice: "Redirecting to the root page" unless current_user == Micropost.find(params[:id]).user
    end
    
    
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    # validates user is correct
    # saves session
    found_user = User.find_by(email: params[:session][:email].downcase)
    if found_user && found_user.authenticate(params[:session][:password])
      flash[:success] = "Successfully signed in"
      sign_in found_user
      redirect_back_or user_path(found_user)
    else
      flash.now[:error] = "Error signing in #{params[:session][:email]}"
      render 'new'
    end       
  end
  
  def destroy
    signout
    redirect_to root_path
  end
  
 
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @user = current_user
      @micropost = current_user.microposts.build
      @feed_items = @user.feed.paginate(page: params[:page], per_page: 10)
    end
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :signed_in_user, only: [:edit, :update, :index]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:destroy]

  def new
    redirect_to user_path(current_user) if signed_in?
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Account successfully created"
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
      User.find(params[:id]).destroy
      flash[:success] = "User deleted"
      redirect_to users_path

  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page], per_page: 10)
  end

  def index
    @users = User.paginate(page: params[:page])
  end



  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "User updated successfully"
      redirect_to @user
    else
      flash[:error] = "User update went wrong"
      render 'edit'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name,:email,:password,:password_confirmation)
    end

    # before filters
    def correct_user
      redirect_to root_url, notice: "Redirecting to the root page" unless current_user == User.find(params[:id])
    end

    def admin_user
      redirect_to root_url unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "AZP"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
  
  
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end
  
  def signout
    self.current_user = nil
    cookies.delete(:remember_token)
  end
  
  def signed_in?
    !current_user.nil?  
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    current_user ||= User.find_by(remember_token: remember_token)
  end
  
  def current_user?(user)
    current_user == user
  end
  
  def store_location
    session[:return_to] = request.url if request.get?
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end


  # before filters
  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in"
    end
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
  def gravatar_for(user, options={size: 40} )
    email_md5_hash = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{email_md5_hash}?s=#{options[:size]}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="#">Amazon product poller</a>
    by Jean Frederic Plante
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" role="navigation">		
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "AZP", root_path, id: "logo" %>
			<nav>
				<ul class="nav pull-right">
					<% if signed_in? %>
					<li> <%= link_to "Users" , users_path %></li>
					<li id="fat-menu" class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							Account <b class="caret"></b>
						</a>
						<ul class="dropdown-menu">				
							<li> <%= link_to "Profile" , user_path(current_user) %></li>	
							<li> <%= link_to "Edit Profile" , edit_user_path(current_user) %></li>									
							<li class="divider"></li>
							<li> <%= link_to "Sign out" , signout_path, method: 'delete' %></li>
						</ul>
					</li>
					
					<% else %>
					<li> <%= link_to "Sign in" , signin_path %></li>
					<% end %>
					<li> <%= link_to "Help" , help_path %></li>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= full_title(yield(:title)) %></title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>

</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |key, value| %>
			<%= content_tag(:div, value, class: "alert alert-#{key}") %>
		<% end %>
		<%= yield %>
		<%= render "layouts/footer"%>
		<%= debug(params) if Rails.env.development? %>
	</div>

</body>
</html>

app/views/microposts/_micropost.html.erb
<li>
<span class="content"> <%= micropost.content %> </span>
<span class="timestamp">Posted <%= time_ago_in_words(micropost.created_at) %> ago </span> 
<% if current_user == micropost.user %>
| <%= link_to 'delete', micropost, method: :delete , data: { confirm: "Are you sure?"}, title: micropost.content %>
<% end %>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
	<div class="alert alert-error">
		The form contains <%= pluralize(object.errors.count, "error")%>
	</div>
	<ul>
		<% object.errors.full_messages.each do |m| %>
		<li> <%= m %> </li>
		<% end %>
	</ul>
</div>
<% end %>

app/views/shared/_feed_item.html.erb
<li	id="#{feed_item.id}">
<span class="user"><%=  link_to gravatar_for(feed_item.user, size: 30), feed_item.user %></span>
	
<span class="content"> <%= feed_item.content %> </span>
<span class="timestamp">Posted by <%= link_to feed_item.user.name, feed_item.user %> <%= time_ago_in_words(feed_item.created_at) %> ago </span> 
<% if current_user == feed_item.user %>
| <%= link_to 'delete', feed_item, method: :delete , data: { confirm: "Are you sure?"}, title: feed_item.content %>
<% end %>
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<div class="field">
	<%= f.text_area :content, placeholder: "Compose your message ... " %>
</div>
		
<%= f.submit "Post", class: "btn btn-large btn-primary" %>
		
<% end %>

app/views/shared/_user_info.html.erb
<%= gravatar_for current_user, size: 52 %>
<h1>
<%= current_user.name %> (<%= current_user.email %>)
</h1>
<span>
	 <%= "Micropost".pluralize(current_user.microposts.count) %>(<%= current_user.microposts.count%>)
</span>
<span>
<%= link_to "My profile", href: current_user %>
</span>

app/views/static_pages/_feed.html.erb
<% if @feed_items.any? %>
<ol class="microposts">
	<%= render partial: "shared/feed_item", collection: @feed_items %>
</ol>
<%= will_paginate @feed_items %>
<% end %>

app/views/static_pages/_landing_page.html.erb
<div class="center hero-unit">
	<h1>Amazon price poller</h1>
	<h2>Don't pay more than you need for your products</h2>
	<%= link_to "Start tracking", signup_path, class: "btn btn-large btn-primary"%>
</div>

app/views/static_pages/_user_home.html.erb
<section>
	<%= render 'shared/user_info' %>
</section>
<section>
	<%= render 'shared/micropost_form' %>
</section>
	

app/views/static_pages/help.html.erb
<% provide(:title,'Help') %>
<h1>Help</h1>

app/views/static_pages/home.html.erb
<% if signed_in? %>
	<div class="row">
		<aside class="span4">
			<%= render "static_pages/user_home" %>
		</aside>	
		<div class="span8">
			<%= render partial: "static_pages/feed" %>
		</div>
	</div>	
<% else %>
	<%= render "landing_page" %>
<% end %>

app/views/users/_user.html.erb
<li>
<%= gravatar_for user, size: 52 %>
<%= user.name %> (<%= user.email %>)
<% if current_user.admin? && !current_user?(user) %>
| <%= link_to 'delete', user, method: :delete , data: { confirm: "Are you sure?"} %>
<% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title,'Edit user') %>
<h1>Edit user</h1>
<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
		<%= render 'shared/error_messages', object: f.object %>
		
		<%= f.label :name %>
		<%= f.text_field :name %>
		
		<%= f.label :email %>
		<%= f.text_field :email %>
		
		<%= f.label :password %>
		<%= f.password_field :password %>
		
		<%= f.label :password_confirmation, "Confirmation" %>
		<%= f.password_field :password_confirmation	 %>
		
		<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
		
		<% end %>
		
		<%= gravatar_for @user %>
		<a href="http://gravatar.com/emails">change</a>
	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, "All users") %>
<h1 id="all_users">All users</h1>

<%= will_paginate %>
<ul class="users">
	<%= render @users %>
</ul>
<%= will_paginate %>
	

app/views/users/new.html.erb
<% provide(:title,'Signup') %>
<h1>Sign up</h1>
<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
		<%= render 'shared/error_messages', object: f.object %>
		
		<%= f.label :name %>
		<%= f.text_field :name %>
		
		<%= f.label :email %>
		<%= f.text_field :email %>
		
		<%= f.label :password %>
		<%= f.password_field :password %>
		
		<%= f.label :password_confirmation, "Confirmation" %>
		<%= f.password_field :password_confirmation	 %>
		
		<%= f.submit "Create new account", class: "btn btn-large btn-primary" %>
		
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
	<aside class="span4">
		<section>
			<h1><%= @user.name %>
			</h1>
			<%= gravatar_for @user %>
			<p><%= @user.email %></p>
		</section>
	</aside>
	<div class="span8">
		<% if @user.microposts.any? %>
		<h3> Microposts(<%=@user.microposts.count%>) </h3>
		<ol class="microposts">
			<%= render @microposts %>
		</ol>
		<%= will_paginate @microposts %>
		<% end %>
	</div>
</div>